'''
#Import the tkinter library
from tkinter import *
from tkinter import ttk

#Create an instance of tkinter frame
win = Tk()

#Set the geometry
win.geometry("600x400")

#Add a class to style the tkinter widgets

style = ttk.Style()
style.configure('TEntry', foreground = 'red')

#Define a function to change the text color
def change_color():
   text.configure(background="red")

#Create a text widget
text=Label(win,text="This is a New Text",foreground="black",
background="yellow",font=('Aerial bold',20))
text.pack(pady=20)

#Create a Button widget
r=ttk.Button(win, text= "A", command= change_color)
r.pack(side=BOTTOM, anchor= NW,pady=10)
rr=ttk.Button(win, text= "O", command= change_color)
rr.pack(side=TOP, )
rrr=ttk.Button(win, text= "OO", command= change_color)
rrr.pack(side = TOP,anchor = NW)
rrrr=ttk.Button(win, text= "O", command= change_color)
rrrr.pack(pady=10)


win.mainloop()
'''
# import tkinter module
from tkinter import *
from tkinter import ttk
from PIL import Image
import matplotlib.pyplot as plt   
# creating main tkinter window/toplevel
master = Tk()
master.geometry("500x600")
master.configure(bg='yellow')
# this will create a label widget
l1 = Label(master, text = "Height")
l2 = Label(master, text = "Width")
  
# grid method to arrange labels in respective
# rows and columns as specified
#l1.grid(row = 0, column = 0, sticky = W, pady = 2)
#l2.grid(row = 1, column = 0, sticky = W, pady = 2)
  
# entry widgets, used to take entry from user
#e1 = Entry(master)
#e2 = Entry(master)
  
# this will arrange entry widgets
#e1.grid(row = 0, column = 1, pady = 2)
#e2.grid(row = 1, column = 1, pady = 2)
def aa():
  

   im = Image.open("A.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("AA.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('apple.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('AA.jpg')
   ff=Image.open('A.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def bb():
  
   im = Image.open("B.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("BB.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('ball.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('BB.jpg')
   ff=Image.open('B.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def cc():
  

   im = Image.open("C.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("cc.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('cat.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('cc.jpg')
   ff=Image.open('C.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def dd():
  
   im = Image.open("D.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("dd.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('dog.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('dd.jpg')
   ff=Image.open('D.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def ee():
  

   im = Image.open("E.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("EE.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('egg.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('EE.jpg')
   ff=Image.open('E.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
#####################################################################
#######################################################################
def ff():
  

   im = Image.open("F.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("ff.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('fish.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('ff.jpg')
   ff=Image.open('F.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def gg():
  
   im = Image.open("g.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("gg.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('goat.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('gg.jpg')
   ff=Image.open('g.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def hh():
  

   im = Image.open("h.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("hh.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('hen.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('hh.jpg')
   ff=Image.open('h.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def ii():
  
   im = Image.open("I.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("ii.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('icecream.png')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('ii.png')
   ff=Image.open('I.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def jj():
  

   im = Image.open("J.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("jj.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('jug.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('jj.jpg')
   ff=Image.open('J.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
#######################################################################
#######################################################################
def kk():
  

   im = Image.open("K.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("KK.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('kite.png')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('KK.jpg')
   ff=Image.open('K.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def ll():
  
   im = Image.open("L.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("LL.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('lion.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('LL.jpg')
   ff=Image.open('L.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def mm():

   im = Image.open("M.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("MM.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('mango.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('MM.png')
   ff=Image.open('M.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def nn():
  
   im = Image.open("N.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("NN.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('nest.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('NN.jpg')
   ff=Image.open('N.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def oo():
  

   im = Image.open("O.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("OO.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('orange.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('OO.png')
   ff=Image.open('O.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
#############################################################
#############################################################
def pp():
  

   im = Image.open("P.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("PP.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('potato.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('PP.png')
   ff=Image.open('P.jpg')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def qq():
  
   im = Image.open("q.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("QQ.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('quilt.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('QQ.png')
   ff=Image.open('q.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def rr():

   im = Image.open("r.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("RR.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('rabbit.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('RR.jpg')
   ff=Image.open('r.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def ss():
  
   im = Image.open("s.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("SS.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('swan.png')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('SS.png')
   ff=Image.open('s.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def tt():
  

   im = Image.open("t.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("TT.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('tortoise.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('TT.png')
   ff=Image.open('t.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

#############################################################
#############################################################
def uu():
  

   im = Image.open("u.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("uu.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('umbrella.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('uu.png')
   ff=Image.open('u.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def vv():
  
   im = Image.open("v.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("vv.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('vase.png')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('v.png')
   ff=Image.open('vv.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def ww():

   im = Image.open("w.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open('ww.png')  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('whale.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('w.png')
   ff=Image.open('ww.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def xx():
  
   im = Image.open("x.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("xx.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('xmas.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('x.png')
   ff=Image.open('xx.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def yy():
  

   im = Image.open("y.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("yy.jpg")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('yatch.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('y.png')
   ff=Image.open('yy.jpg')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()

def zz():

  

   im = Image.open("z.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   im = Image.open("zz.png")  
   plt.imshow(im)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   imm = Image.open('for.png')
   plt.imshow(imm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   immm = Image.open('zip.jpg')
   plt.imshow(immm)
   plt.show(block=False)
   plt.pause(1)
   plt.close()
   f=Image.open('z.png')
   ff=Image.open('zz.png')
   plt.subplot(2,2,1)
   plt.imshow(ff)
   plt.subplot(2,2,2)
   plt.imshow(f)
   plt.show()
def chart():
   im=Image.open('chart.png')
   plt.imshow(im)
   plt.show()

# checkbutton widget
c1 = Checkbutton(master, text = "Preserve")
c1.grid(row = 2, column = 0, sticky = W, )
a=ttk.Button(master, text= "A",command=aa)
a.grid(row = 3, column = 2)
b=ttk.Button(master, text= "B", command=bb)
b.grid(row = 3, column = 3)
c=ttk.Button(master, text= "C",command=cc)
c.grid(row = 3, column =4)
d=ttk.Button(master, text= "D",command=dd)
d.grid(row = 3, column =5)
e=ttk.Button(master, text= "E",command=ee)
e.grid(row = 3, column= 6)
##############################################
# adding image (remember image should be PNG and not JPG)

f=ttk.Button(master, text= "F",command=ff)
f.grid(row = 4, column = 2)
b=ttk.Button(master, text= "G", command=gg)
b.grid(row = 4, column = 3)
c=ttk.Button(master, text= "H",command=hh)
c.grid(row = 4, column =4)
d=ttk.Button(master, text= "I",command=ii)
d.grid(row = 4, column =5)
e=ttk.Button(master, text= "J",command=jj)
e.grid(row = 4, column= 6)

####################################################


o=ttk.Button(master, text= "K",command=kk)
o.grid(row = 5, column = 2)
b=ttk.Button(master, text= "L", command=ll)
b.grid(row = 5, column = 3)
c=ttk.Button(master, text= "M",command=mm)
c.grid(row = 5, column =4)
d=ttk.Button(master, text= "N",command=nn)
d.grid(row = 5, column =5)
e=ttk.Button(master, text= "O",command=oo)
e.grid(row = 5, column= 6)
##################################################

o=ttk.Button(master, text= "P",command=pp)
o.grid(row = 6, column = 2)
b=ttk.Button(master, text= "Q", command=qq)
b.grid(row = 6, column = 3)
c=ttk.Button(master, text= "R",command=rr)
c.grid(row = 6, column =4)
d=ttk.Button(master, text= "S",command=ss)
d.grid(row = 6, column =5)
e=ttk.Button(master, text= "T",command=tt)
e.grid(row = 6, column= 6)

##################################################

o=ttk.Button(master, text= "U",command=uu)
o.grid(row = 6, column = 2)
b=ttk.Button(master, text= "V", command=vv)
b.grid(row = 6, column = 3)
c=ttk.Button(master, text= "W",command=ww)
c.grid(row = 6, column =4)
d=ttk.Button(master, text= "X",command=xx)
d.grid(row = 6, column =5)
e=ttk.Button(master, text= "Y",command=yy)
e.grid(row = 6, column= 6)
z=ttk.Button(master,text='Z', command=zz)
z.grid(row=7,column=2)
ch=ttk.Button(master,text='chart',command=chart)
ch.grid(row=7,column=6)
mainloop()